name: Bot de Búsqueda Automática

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código del repositorio
        uses: actions/checkout@v4

      - name: Configurar entorno de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm install

      - name: Verificar y ejecutar el bot
        env:
          BOT_TOKEN: ${{ secrets.JJM1 }}
        run: |
          if [ -z "$BOT_TOKEN" ]; then
            echo "::error::El secreto JJM1 está vacío o no fue encontrado en GitHub Secrets."
            exit 1
          fi
          echo "Secreto detectado correctamente. Iniciando script..."
          node index.js
