name: Bot de Búsqueda Automática

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código del repositorio
        uses: actions/checkout@v4

      - name: Configurar entorno de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar script de búsqueda
        env:
          BOT_TOKEN: ${{ secrets.JJM1 }}
        run: node index.js
